version: '2'
services:
    nginx:
        image: "nginx:1.13-alpine"
        ports:
            - '12002:80'
        volumes:
            - './dist:/usr/share/nginx/html:ro'
            - './server/nginx.conf:/etc/nginx/nginx.conf:ro' 

    expo:
        image: expo/web
        build: .
        ports:
            - '4200:4200' # default port
        volumes:
            - './:/usr/dockers/expo/'
        entrypoint: Docker/docker-entrypoint.sh
        
